#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 01 02 03

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

monitor_1=$(xrandr | grep "DP-1-9")
monitor_2=$(xrandr | grep "DP-1-8")
if [[ $monitor_1 = *connected* ]] && [[ $monitor_2 = *connected* ]]; then
  xrandr --output eDP-1 --mode 1536x1024 --rotate normal --output DP-1-9 --primary --mode 1920x1080 --rotate normal --left-of eDP-1 --output DP-1-8 --mode 1920x1080 --rotate normal --left-of DP-1-9
fi

if type "xrandr"; then
  for m in $(xrandr | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload example & 
  done
else
  polybar --reload example &
fi

nitrogen --restore
